version: '3.8'

services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: torypto-backend
    volumes:
      - ../../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=torypto
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - WC_API_URL=${WC_API_URL}
      - WC_CONSUMER_KEY=${WC_CONSUMER_KEY}
      - WC_CONSUMER_SECRET=${WC_CONSUMER_SECRET}
    networks:
      - torypto-network
    restart: unless-stopped

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: torypto-frontend
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - torypto-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: torypto-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=torypto
    networks:
      - torypto-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: torypto-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - torypto-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: torypto-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@torypto.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - torypto-network
    restart: unless-stopped

networks:
  torypto-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 